lib/nano_planner_web/router.ex
defmodule NanoPlannerWeb.Router do
  use NanoPlannerWeb, :router

  import NanoPlannerWeb.UserAuth,
    only: [
      redirect_if_user_is_authenticated: 2,
      require_authenticated_user: 2
    ]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :pre_auth do
    plug NanoPlannerWeb.CurrentUser
    plug :redirect_if_user_is_authenticated
  end

  pipeline :restricted do
    plug NanoPlannerWeb.CurrentUser
    plug :require_authenticated_user
  end

  scope "/", NanoPlannerWeb do
    pipe_through :browser

    get "/lessons/form", LessonController, :form
    get "/lessons/register", LessonController, :register
    get "/lessons/hello", LessonController, :hello
    get "/cookie", CookieController, :show
    get "/cookie/set", CookieController, :set
    get "/cookie/unset", CookieController, :unset
    get "/session", SessionController, :show
    get "/session/set", SessionController, :set
    get "/session/unset", SessionController, :unset
    get "/plug", PlugController, :show
  end

  scope "/", NanoPlannerWeb do
    pipe_through [:browser, NanoPlannerWeb.CurrentUser]

    get "/", TopController, :index
  end

  scope "/", NanoPlannerWeb do
    pipe_through [:browser, :pre_auth]

    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
  end

  scope "/", NanoPlannerWeb do
    pipe_through [:browser, :restricted]
    
    scope "/plan_items" do
      get "/of_today", PlanItemController, :of_today
    end

    resources "/plan_items", PlanItemController
    delete "/users/log_out", UserSessionController, :delete
  end
end

lib/nano_planner_web/controllers/top_controller.ex
defmodule NanoPlannerWeb.TopController do
  use NanoPlannerWeb, :controller

  def index(conn, _params) do
    if conn.assigns[:current_user] do
      render(conn, "index.html")
    else
      render(conn, "welcome.html")
    end
  end
end

lib/nano_planner_web/views/top_view.ex
defmodule NanoPlannerWeb.TopView do
  use NanoPlannerWeb, :view

  def document_title(_assigns) do
    "NanoPlanner"
  end
end

lib/nano_planner_web/templates/top/index.html.eex
<div class="list-group">
  <%= link to: Routes.plan_item_path(@conn, :index),
    class: "list-group-item" do %>
    <i class="fa fa-list"></i> 予定表
  <% end %>
  <%= link to: Routes.plan_item_path(@conn, :of_today),
    class: "list-group-item" do %>
    <i class="fa fa-list"></i> 今日の予定表
  <% end %>
  <%= link to: Routes.plan_item_path(@conn, :new), 
    class: "list-group-item" do %>
    <i class="fa fa-plus"></i> 予定の追加
  <% end %>
</div>

lib/nano_planner_web/templates/top/welcome.html.eex
<div class="jumbotron">
  <h1 class="display-4">Welcome to NanoPlanner!</h1>
  <hr class="my-4">
  <%= link to: Routes.user_session_path(@conn, :new),
    class: "btn btn-lg btn-primary" do %>
    <i class="fa fa-sign-in-alt"></i> ログイン
  <% end %>
</div>