lib/nano_planner_web/router.ex
defmodule NanoPlannerWeb.Router do
  use NanoPlannerWeb, :router

  import NanoPlannerWeb.UserAuth,
    only: [
      redirect_if_user_is_authenticated: 2,
      require_authenticated_user: 2
    ]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :pre_auth do
    plug NanoPlannerWeb.CurrentUser
    plug :redirect_if_user_is_authenticated
  end

  pipeline :restricted do
    plug NanoPlannerWeb.CurrentUser
    plug :require_authenticated_user
  end

  scope "/", NanoPlannerWeb do
    pipe_through :browser

    get "/lessons/form", LessonController, :form
    get "/lessons/register", LessonController, :register
    get "/lessons/hello", LessonController, :hello
    get "/cookie", CookieController, :show
    get "/cookie/set", CookieController, :set
    get "/cookie/unset", CookieController, :unset
    get "/session", SessionController, :show
    get "/session/set", SessionController, :set
    get "/session/unset", SessionController, :unset
    get "/plug", PlugController, :show
  end

  scope "/", NanoPlannerWeb do
    pipe_through [:browser, NanoPlannerWeb.CurrentUser]

    get "/", TopController, :index
  end

  scope "/", NanoPlannerWeb do
    pipe_through [:browser, :pre_auth]

    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
  end

  scope "/", NanoPlannerWeb do
    pipe_through [:browser, :restricted]
    
    scope "/plan_items" do
      get "/of_today", PlanItemController, :of_today
    end

    resources "/plan_items", PlanItemController
    delete "/users/log_out", UserSessionController, :delete
  end
end

lib/nano_planner_web/views/layout_view.ex
defmodule NanoPlannerWeb.LayoutView do
  use NanoPlannerWeb, :view

  def this_year do
    time_zone = Application.get_env(:nano_planner, :default_time_zone)
    DateTime.now!(time_zone).year
  end
end

lib/nano_planner_web/templates/layout/_flash_messages.html.eex
<%= if info = get_flash(@conn, :info) do %>
  <p class="alert alert-success"><%= info %></p>
<% end %>
<%= if error = get_flash(@conn, :error) do %>
  <p class="alert alert-danger"><%= error %></p>
<% end %>

lib/nano_planner_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= @view_module.document_title(assigns) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="icon" type="image/x-icon"
      href="<%= Routes.static_path(@conn, "/images/nano_planner.ico") %>"/>
    <link rel="apple-touch-icon" type="image/x-icon"
      href="<%= Routes.static_path(@conn, "/images/clock256.png") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="d-flex justify-content-between">
      <h1>
        <%= link "NanoPlanner", to: Routes.top_path(@conn, :index, []) %>
      </h1>
      <%= if @conn.assigns[:current_user] do %>
        <div class="m-2">
          <%= link to: Routes.user_session_path(@conn, :delete), method: :delete do %>
            <i class="fa fa-sign-out-alt"></i> ログアウト
          <% end %>
        </div>
      <% end %>
    </header>
    <main>
      <%= render "_flash_messages.html", conn: @conn %>
      <%= @inner_content %>
    </main>
    <footer>
      &copy; <%= this_year() %> Coregenik Inc.
    </footer>
  </body>
</html>